### ISSUE TITLE
询问论文细节

### ISSUE THREAD

**Issue by splinter21** [ChaofWang/AWSRN#1]
1、P7表格中的ours指标是否使用self-ensemble?
2、我使用https://github.com/ceykmc/pytorch_model_summary
脚本，3x16x16作为输入，得到2x的AWSRN模型，理论Madd 712,361,984，换算到论文中的1280x720（*3600）， 是2565G左右，但是论文中是320.5G，相差很远，我们的统计方式是哪里有不同？
3、Table4中，没看懂3579后的那一列数字是指什么，是训练完后的scale值吗？WDSR里面各个分支都有足够多权重，但是AWSRN-B中7x7却几乎零权重，这个是理论上是零，还是巧合？后面表格中MAdd和参数量有没有统计这条支路？可以不统计这条支路，指标可以更好看。

**Comment by ChaofWang** [comment]
你好,感谢你的关注.
1.表格中的结果,我们均**未使用**self-ensemble.你可以下载我提供的模型进行测试.如果想看下self-ensemble的结果,可以在命令行中加入--self-ensemble获取对应的结果.

2.我没有详细查看你提供的这个脚本.但从结果上来看,这个脚本计算conv的方式应该是**2*H*W*param**,其实H,W为输入尺寸.一个MAC算2个ops。但有些不会把这个2计算进去,就例如ResNet50原文中的flops是约4G,但你使用的这个脚本里计算得到已经是8G了.我在计算的时候的时候也没有乘上这个2.应该是这个引起的不一致.另外我们的论文使用的1280x720是指输出的SR尺寸.所以计算x2的时候,你需要把输出的H,W各除以2作为输入.所以根据上面的两者,你的2565G应该是需要除以8. 你可以验证下其他网络,例如VDSR,这类比较简单的网络.VDSR的输入是插值放大的LR,输出也是同样尺寸.其只有conv,所以可计算madd: 665K*1280x720≈612G

3.3579后的那列数字就是训练完成后的scale值.7x7支路为几乎为零,确实我也留意过这个问题.几乎为0,应该只是个巧合.但AWMS上都会有这么个趋势越大的kernel size其权重会越小. 后面计算的参数和madd**均包含这个支路**.事实上,对于最后这部分AWMS,我们希望强调的是,多尺度中每个尺度对于重建的增益是不同的.加入Adaptive weights就是为了区分他们的增益.同时为了这部分带来的额外的参数提供一个更直观可裁剪的参考.这也是Table4想表明的目的.

**Comment by splinter21** [comment]
嗯，明白了,以后用这个脚本还是按除以二算

我这边的网络，结尾加上AWMS，提高不多，4个scale在0.07和0.27之间
只加3x3和5x5，指标反而比纯3x3下降，scale分别是0.3多和0.2多
看来7x7权重为零是巧合了，最后统计参数量也不好删掉，因为不是适用所有的网络都能删除
不过我觉得有必要加上控制参数和计算量的对照实验
这个是轻量网络，虽然是基于32的channels（相比EDSR base block的结构，非base block的参数和计算成本减少了很多），但是3x3+5x5+7x7+9x9，参数量和计算量应该够多加2个多base block了，现在是16个base block，2个的提升应该还是有一些的

**Comment by splinter21** [comment]
有关wSE的比较，
我看了下引用的《Residual Convolutional Neural Network Revisited with Active Weighted Mapping》论文，指的是把输入输出池化concat后经过2次fc和sigmoid变成作残差的input和output的scale参数，不知道我的理解是否正确
然后通过对照实验，证明这个直接2个参数自己学就可以，没必要通过2次fc指导学习，指标一样

开始我以为是RCAN里面的那个CA，后来仔细看了下发现并不是同一个东西。不过还是希望你的指标能超过加CA的，毕竟加CA的计算成本其实加的并不大

**Comment by ChaofWang** [comment]
是的，你理解的是正确的。wSE就是这论文里的AWM。只是在我们的论文里有一个非常类似的名字AWMS，所以怕搞混换了个名字。但关于CA这一点，我理解你的意思，由于wSE的对比的存在，看上去我们的AWRU好像容易联想到对比CA的方式。但实际上我们的AWRU和CA并不只能二者选一的方式存在，他们是可以并存的。我们的AWRU的也不是出于attention的考虑，也不需要用CA再去抬升指标，因为这对论文提出的内容没任何帮助。可以把我们的这种方式理解成“可学习”的residual scaling。而对比wSE，是因为有类似的工作且这种方式也是非常常见且使用的op。

**Comment by coolKeen** [comment]
@ChaofWang 您好，非常感谢您的论文和代码分享。我想追加些论文理解过程里的问题：
1. 我想请问下您是拿Set5,Set14...Urban100这几个当验证集用还是当测试集用，因为我在论文里面没有看到关于验证集是怎么指定的语句，只是看到4.1节那里说“During testing stage, several standard benchmark datasets, namely Set5 [24], Set14 [25], B100 [26], Urban100 [28], Manga109 [27], were used for evaluation”。所以比较疑惑就是您是拿DIV2K里的所有800张图像都去训练，然后直接拿Set5,Set14...Urban100当验证集用的吗（如果是这样，table 5里的psnr就应该是验证集的得分了吧）？
2. table 1的psnr是在哪个数据集里算的？
3. 还有就是整个训练过程迭代了多少次呀？
非常感谢！

**Comment by ChaofWang** [comment]
@coolKeen 你好
1、论文里所有的都是测试集的结果，验证集是DIV2K另外的100张图片。验证集论文里没有关注其结果。
2、table 1是Set5,Set14...Urban100五个测试集的结果的均值，table 5是详细的测试集结果
3、训练命令README里有。https://github.com/ChaofWang/AWSRN#train

**Comment by coolKeen** [comment]
> @coolKeen 你好
> 1、论文里所有的都是测试集的结果，验证集是DIV2K另外的100张图片。验证集论文里没有关注其结果。
> 2、table 1是Set5,Set14...Urban100五个测试集的结果的均值，table 5是详细的测试集结果
> 3、训练命令README里有。https://github.com/ChaofWang/AWSRN#train

@ChaofWang  非常感谢您的回复。我最近发现一个比较麻烦的问题是，您这边计算psnr的代码计算出来的psnr的值好像是要比[FALSR计算psnr的代码](https://github.com/falsr/FALSR/blob/master/calculate.py)计算出来的值要偏高的。这样会导致不公平比较吧。您可以尝试下使用FALSR那里计算psnr的代码计算下psnr，他那边使用的是skimage.color中的compare_psnr计算的，calculate_metrics中hr_y_list和sr_y_list都是提取出ycbcr中的y值的列表，因为您这边输出的rgb值，您可以试下用这份代码计算下（链接 https://pan.baidu.com/s/1w6YGJnKtyIaNREgB-sAXjQ 提取码：vcbe ）。
还有就是您那边计算ssim的代码我看了看也没有找到。不知道是否可以提供下。
非常感谢！

**Comment by ChaofWang** [comment]
@coolKeen 非常感谢你的指出。我确实没有留意到FALSR的这一点。但我没记错的话，skimage下计算的SSIM结果较matlab下的结果偏高。可以参考MSRN。psnr计算的不一致主要是由于rgb转rgb2ycbcr时使用的转换矩阵不一致导致的。所以为了对齐这种差异，目前大部分论文都是采用在matlab上进行转换然后在计算psnr的。我的代码里，虽然是用python实现的，但是是和matlab上转换是一致的，这点我在README的[note2](https://github.com/ChaofWang/AWSRN#note) 已经说明了。如果我转换到skimage下的话就没法和其他大部分的论文结果对齐，比如MSRN，CARN，SRSRMDNF，MEMNet等等。另外比如RCAN, RDN，EDSR的结果同样也是matlab版本计算 的。留意下MSRN，他paper中对应的结果是skimage，导致了SSIM偏高。所以作者重新又评测了一份matlab上的版本，我论文中引用的也是用的他matlab的版本。有时间的话我会重新计算下FALSE的结果。非常感谢

**Comment by coolKeen** [comment]
@ChaofWang 谢谢您的回复。我想再确定下是，现在计算大部分论文计算psnr都是用https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/utility.py#L164 这个函数计算的了吧？然后sr和hr都是（N,C,H,W）大小，且是rgb空间的，还有就是值的range是在[0,rgb_range]的？

**Comment by ChaofWang** [comment]
> @ChaofWang 谢谢您的回复。我想再确定下是，现在计算大部分论文计算psnr都是用
> 
> https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/utility.py#L164
> 
> 这个函数计算的了吧？然后sr和hr都是（N,C,H,W）大小，且是rgb空间的，还有就是值的range是在[0,rgb_range]的？

是的，你可以对比下这个函数计算的psnr是否和这个脚本计算的一致。https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/experiment/Evaluate_PSNR_SSIM.m#L1 rgb_range就是255。我验证过AWSRN和RCAN在这两个计算方式上至少结果是一致的

**Comment by coolKeen** [comment]
@ChaofWang 好的，谢谢。还有最后一个问题想请教下您，如果我用rgb做模型输入，ycbcr的y做模型输出（y是用skimage.color里的rgb2ycbcr函数计算出来的），那么在计算psnr的时候用这个函数是不是也直接就calc_psnr(sr, hr, scale, rgb_range=255, benchmark=True)就可以了，这样算出来的psnr和用rgb做输出算出来的psnr是否可以相互比较？

**Comment by ChaofWang** [comment]
@coolKeen 这样应该也是有差异的，skimage的rgb2ycbcr转换矩阵和matlab上的rgb2ycbcr是不一样的，所以转换后的Y实际上已经不一样了。
我这里的calc_psnr内有带RGB转ycbcr的矩阵，这个是和matlab是一致的
https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/utility.py#L170

**Comment by coolKeen** [comment]
@ChaofWang 好的，再次感谢您。

**Comment by userzm** [comment]
1.作者你好，请问论文里多次用到了wn，这样做的目的仅仅是为了提高训练速度吗，还是说在效果上也有提升了

**Comment by ChaofWang** [comment]
WN本身并不能对性能提升有帮助。大的学习率才对性能提升有帮助。WN本身帮助大学习率情况下 不那么容易产生爆炸。所以在大学习率情况下只要不爆炸 不用WN也是可以的。


| |
wangchaofeng
邮箱：syusuke0511@163.com
|

Signature is customized by Netease Mail Master

在2019年09月03日 10:23，Areil 写道：

1.作者你好，请问论文里多次用到了wn，这样做的目的仅仅是为了提高训练速度吗，还是说在效果上也有提升了

**Comment by userzm** [comment]
好的，谢谢。还有两个问题想请教下您：
1.论文里将LR图片直接卷积然后上采样与主干分支上采样的结果相加，这里的LR图片直接卷积上采样分支是起什么作用了，为什么要这样设计？
2.AWRU里的residual scaling和CA相比，哪种方式加到网络里效果更好呢？看起来residual scaling比CA方式的计算量还要小，是只能二选一吗？如果两个搭配起来用，指标会不会有提升？如果可以搭配，请问如何结合使用比较好，因为功能感觉比较类似？

**Comment by ChaofWang** [comment]
@userzm, 你好
1.LR直接上采样这种方式是WDSR引过来的，WDSR中的改进是基于EDSR中具有相对较高的代价全局残差路径。其实可以使用代价更低的bicubic来替换。当然由于本文中使用的都是由bicubic降质的训练测试，所以直接使用bicubic上采样来训练可能不会有太大差异。但如果换成其他类型的降质方式那么bicubic上采样和WDSR的这种卷积上采样相比并不一定会有类似的效果了。
2.这一点, 可以参考上面的[回复](https://github.com/ChaofWang/AWSRN/issues/1#issuecomment-491644277)。当然我之后也尝试过CA和AWRU一起使用以及用CA替换AWRU中的residual scaling，至少在我的尝试中并未明显的效果。其实可以把residual scaling看做是一种解释CA的方式，可以思考下RCAN中并未使用residual scaling却能在训练如此深的网络时不产生爆炸的原因。
