### ISSUE TITLE
compare with WDSR and EDSR 

### ISSUE THREAD

**Issue by zhengsx** [ChaofWang/AWSRN#10]
Hi, thanks for the code. I notice that your model is developed by WDSR, would you please provide the comparision results with WDSR and EDSR? Thanks.

https://github.com/JiahuiYu/wdsr_ntire2018/blob/master/wdsr_b.py

**Comment by ChaofWang** [comment]
@zhengsx  hello, in the paper, we add a comparison of our model and WDSR baseline. EDSR is a model with a large amount of parameters. So we didn't compare it to our model. But you can compare the baseline of WDSR and EDSR on the x2 scale on the DIV2K val dataset.

Network | Parameters | DIV2K (val) PSNR
-- | -- | --
EDSR Baseline | 1,372,318 | 34.61
WDSR Baseline | 1,190,100 | 34.77
AWSRN | 1,396,872 | 34.81

**Comment by zhengsx** [comment]
I'm very appreciate that.
