### ISSUE TITLE
 How to compute the flops and params ?

### ISSUE THREAD

**Issue by sureJ0824** [ChaofWang/AWSRN#11]
sorry to disturb you , I am interested in the lightweight network too. But I hardly find good codes to compute the flops , params and depth for my network. So can you provide you code about that for references. Thks a lot

**Comment by ChaofWang** [comment]
@sureJ0824  hello, You can look here #8 .  I have not used any calculation scripts or libraries to calculate Mutiadds. I calculated it by myself. The calculation is roughly estimated as HxWxparams.  And I think this script may be a good choice https://github.com/Lyken17/pytorch-OpCounter

**Comment by sureJ0824** [comment]
Thanks so much. That must be helpful for me.

**Comment by sureJ0824** [comment]
Sorry, but It's me again.
I am using the EDSR-PyTorch code
and I am a little confused about the flops of its meanshift_lay
 Can you show me the code about it, thank you so much
QAQ

**Comment by ChaofWang** [comment]
@sureJ0824 hello，you can just remove this layer. Its impact on flops can be ignored

**Comment by sureJ0824** [comment]
ok~got it~
Thanks~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WangChaofeng"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 晚上6:39
收件人: "ChaofWang/AWSRN"<AWSRN@noreply.github.com&gt;; 
抄送: "1226510143"<1226510143@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ChaofWang/AWSRN]  How to compute the flops and params ? (#11)




@sureJ0824 hello，you can just remove this layer. Its impact on flops can be ignored
