### ISSUE TITLE
DIV2K scale x8数据集

### ISSUE THREAD

**Issue by sureJ0824** [ChaofWang/AWSRN#12]
你好~
我在官网上没有看到x8的数据集，想问您一下您做x8的时候用的数据集是自己用matlab处理得到的吗？
在训练scale x8的模型的时候需要对代码中的data部分做一些特殊的修改吗？还是直接将数据集放进去就可以用？
打扰啦

**Comment by ChaofWang** [comment]
你好，X8是ntire18的赛道，你可以在这里找到数据[X8](https://data.vision.ee.ethz.ch/cvl/DIV2K/)。训练的时候不需要对data进行修改，直接指定scale就行

**Comment by sureJ0824** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WangChaofeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 上午9:20
收件人:&nbsp;"ChaofWang/AWSRN"<AWSRN@noreply.github.com&gt;;
抄送:&nbsp;"1226510143"<1226510143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChaofWang/AWSRN] DIV2K scale x8数据集 (#12)




你好，X8是ntire18的赛道，你可以在这里找到数据https://data.vision.ee.ethz.ch/cvl/DIV2K/。训练的时候不需要对data进行修改，直接指定scale就行
