### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Bayrambai** [ChaofWang/AWSRN#3]
I am getting following error while running the training script:
"ImportError: cannot import name '_worker_manager_loop'"
My pytorch version is 1.0.1.

**Comment by ChaofWang** [comment]
Hello, this version still has some problems with Pytorch 1.0. You can consider using 0.4.1 or refer to [here](https://github.com/thstkdgus35/EDSR-PyTorch). I have not tried in detail whether there are still other problems, but for you this should directly replace dataloader.py with [this](https://github.com/thstkdgus35/EDSR-PyTorch/blob/legacy/1.0.0/src/dataloader.py).

**Comment by Bayrambai** [comment]
Thank you very much! I follow that instructions it has its own problems :)
