### ISSUE TITLE
Some questions about Data specifications in option.py

### ISSUE THREAD

**Issue by wehkjhkl** [ChaofWang/AWSRN#4]
I want to train my own data,but i don't know how to place my data in a correct dataset. Do you mean i should place training data and test data in one folder,but the number is different?must I have lr dataset directory?

**Comment by ChaofWang** [comment]
If you train your own data, you can rewrite a dataset by srdata.py without having to follow my data format.
Mainly modify these items: [#L13](https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/data/srdata.py#L13),[#L146](https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/data/srdata.py#L146),[#L157](https://github.com/ChaofWang/AWSRN/blob/bb6e2b0cff78182c5a4cc536ecea14e2f59ade0c/code/src/data/srdata.py#L157)

**Comment by wehkjhkl** [comment]
OK, thank you!
