### ISSUE TITLE
MultiAdds

### ISSUE THREAD

**Issue by dujuan1999** [ChaofWang/AWSRN#8]
@ChaofWang Hello, could you please tell me your test code of MultAdds, I used the thop library, and the measured data are quite different from those in your paper.Thanks!

**Comment by ChaofWang** [comment]
> @ChaofWang Hello, could you please tell me your test code of MultAdds, I used the thop library, and the measured data are quite different from those in your paper.Thanks!

hello, Could tell me the results you tested? You can look here #7 #6 #5  #1

**Comment by dujuan1999** [comment]
> > @ChaofWang您好，请您告诉我您的MultAdds测试代码，我使用了thop库，测量数据与您论文中的数据完全不同。谢谢！
> 
> 你好，可以告诉我你测试的结果吗？你可以看看[＃7 ](https://github.com/ChaofWang/AWSRN/issues/7) [＃6 ](https://github.com/ChaofWang/AWSRN/issues/6) [＃5 ](https://github.com/ChaofWang/AWSRN/issues/5) [＃1](https://github.com/ChaofWang/AWSRN/issues/1)

I tested  AWSRN x3. The parameters are the same as in the paper, but MutiAdds is 169.7G

**Comment by ChaofWang** [comment]
@dujuan1999 hello, I have not used any calculation scripts or libraries to calculate Mutiadds. I calculated it by myself. The calculation is roughly estimated as HxWxparams. I just used the chop library you said, and it seems that the results are the same.

`Flops:   150.62482944
Params:  1476103.0`

**Comment by dujuan1999** [comment]
> @dujuan1999 hello, I have not used any calculation scripts or libraries to calculate Mutiadds. I calculated it by myself. The calculation is roughly estimated as HxWxparams. I just used the chop library you said, and it seems that the results are the same.
> 
> `Flops: 150.62482944 Params: 1476103.0`

I found my mistake, I gave the wrong size.Now, the flops is fine.Thank you very much for your help.

**Comment by Auth0rM0rgan** [comment]
Hey @ChaofWang ,

Would you please tell me how to use thop library?! because I faced an error which thop not support Pixelshuffle when I'm trying to use it. 

Thanks!

**Comment by ChaofWang** [comment]
> Hey @ChaofWang ,
> 
> Would you please tell me how to use thop library?! because I faced an error which thop not support Pixelshuffle when I'm trying to use it.
> 
> Thanks!


u can append Pixelshuffle in register_hooks at thop/profile.py and add this count function at thop/count_hooks.py

def count_pixelshuffle(m, x, y):
    x = x[0]
    nelements = x.numel()
    total_ops = nelements
    m.total_ops = torch.Tensor([int(total_ops)])

**Comment by xiaotian3** [comment]
> > > @ChaofWang您好，请您告诉我您的MultAdds测试代码，我使用了thop库，测量数据与您论文中的数据完全不同。谢谢！
> > 
> > 
> > 你好，可以告诉我你测试的结果吗？你可以看看[＃7 ](https://github.com/ChaofWang/AWSRN/issues/7) [＃6 ](https://github.com/ChaofWang/AWSRN/issues/6) [＃5 ](https://github.com/ChaofWang/AWSRN/issues/5) [＃1](https://github.com/ChaofWang/AWSRN/issues/1)
> 
> I tested AWSRN x3. The parameters are the same as in the paper, but MutiAdds is 169.7G

您好，能提供下您测试的参数的代码吗？
